#
# Use this as a starting point for setting up our basic NodeJS app.
# Think about the directives we covered in the slides, which would best
# complete each item in out TODO list below?
#
# Hint:
# What needs to be done::
#
# 1. The base image (use 'node:lts-alpine')
# 2. Copy the package.json file to the container app root
# 3. Install dependencies (hint: use `npm install`)
# 4. Copy our app code into the container
# 5. Expose the port we should use to access this container
# 6. Define our default command (hint: the shell equivalent is `node app.js`)
#

# Base image directive should go here.

# Create app directory
WORKDIR /home/node/app

# Everything else should go here
